server:
  servlet:
    context-path: /api

spring:
  application:
    name: ${SERVICE_NAME}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 1000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_MYSQL_ID}
    password: ${DB_MYSQL_PASSWORD}
    url: jdbc:mysql://${DB_MYSQL_HOST}:${DB_MYSQL_PORT}/${DB_MYSQL_DATABASE}
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 20
      minimum-idle: 10

  data:

#    mongodb:
#      database: ${MONGODB_DATABASE}
#      uri: ${MONGODB_URI}

  cache:
    redis:
      host: ${REDIS_CACHE_HOST}
      port: ${REDIS_CACHE_PORT}
      password: ${REDIS_CACHE_PASSWORD}
      ttl-minutes: 1440

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQLDialect

  auth:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY}
      refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY}
      sign-up-token-expiry: ${JWT_SIGN_UP_TOKEN_EXPIRY}



cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

batch-redis:
  host: ${REDIS_BATCH_HOST}
  port: ${REDIS_BATCH_PORT}
  password: ${REDIS_BATCH_PASSWORD}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui.html
    url: /api/v3/api-docs
    config-url: /api/v3/api-docs/swagger-config
    display-request-duration: true
    filter: true
    doc-expansion: none
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    persist-authorization: true

firebase:
  config:
    path: firebase-service-key.json
